name: Deploy Flutter Web to GitHub Pages

# Executa o script toda vez que um push for feito na branch main
on:
  push:
    branches:
      - main

# Permissões estritamente necessárias para o GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Setup do Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Dependências
        run: flutter pub get

      # ATENÇÃO ALUNOS: O base-href DEVE ser exatamente o nome do repositório!
      - name: Build Flutter Web
        run: flutter build web --release --base-href "/exercicio-flutter-docker/"

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4 # Atualizado para v4

      - name: Upload do Artefato
        uses: actions/upload-pages-artifact@v3 # Atualizado para v3 (última versão disponível desta action)
        with:
          # O caminho aponta para a pasta que o Flutter acabou de gerar
          path: 'build/web'

      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Atualizado para v4