name: Deploy Pages

on:
  workflow_run:
    workflows:
      - "Build Web"  # deve ser exatamente o "name:" do workflow de build
    types:
      - completed
    branches:
      - main

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    name: Publicar no GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy para o GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
